      <h1>Alarm Events</h1>
      Current System state is <?php echo $this->alarmState->eventText ?><br/>
<?php
echo '<div class="span4">';
echo '<h2>System</h2>';
$lastEvent = '';
echo '<ul>';
foreach($this->systemEvents as $event) {
    if ($lastEvent != $event->eventText) {
        $eventTime = new DateTime($event->eventTimestamp);
        echo '<li class="event'.$event->eventTypeID.'">', $event->eventText , '&nbsp;by&nbsp;', $event->real_name,' - ' , str_replace(' ', '&nbsp;', $eventTime->format('m/d/Y g:i:s A')) , '</li>';
        $lastEvent = $event->eventText;
    }
}
echo '</ul>';
echo '</div>';

echo '<div class="span4">';
echo '<ul>';

$lastDate = '';
foreach($this->events as $doorEvent) {
	$eventDate = new DateTime($this->events->current()->eventTimestamp);
	$eventDate = $eventDate->format('m/d/Y');
	if ($lastDate != $eventDate) {
		$lastDate = $eventDate;
		echo "<h4>$eventDate</h4>";
	}
	$lastEvent = '';
		$eventTime = new DateTime($doorEvent->eventTimestamp);
		$eventTxt = $doorEvent->doorName. ' ' . $doorEvent->eventText;
		$eventTxt = str_replace('door door', 'door', $eventTxt);
		echo '<li class="event'.$doorEvent->eventTypeID.'">',$eventTxt , ' - ' , str_replace(' ', '&nbsp;', $eventTime->format('g:i:s A')) , '</li>';
		if ($this->eventTable->hasVideo($doorEvent->eventID)) {
		    echo '<video width="280" controls>';
		    echo '   <source src="/video/index/eventid/'.$doorEvent->eventID.'" type="video/webm">';
		    echo '</video>';
		}
}		
echo '</ul>';
echo '</div>';
?>
