      <h1>Alarm Events</h1>
      Current System state is <?php echo $this->alarmState->eventText ?><br/>
<?php
echo '<div class="span4">';
echo '<h2>System</h2>';
$lastEvent = '';
echo '<ul>';
foreach($this->systemEvents as $event) {
    if ($lastEvent != $event->eventText) {
        $eventTime = new DateTime($event->eventTimestamp);
        echo '<li class="event'.$event->eventTypeID.'">', $event->eventText , '&nbsp;by&nbsp;', $event->real_name,' - ' , str_replace(' ', '&nbsp;', $eventTime->format('m/d/Y g:i:s A')) , '</li>';
        $lastEvent = $event->eventText;
    }
}
echo '</ul>';
echo '</div>';

foreach($this->events as $doorEvents) {
	echo '<div class="span4">';
	echo '<h2>' , $doorEvents->current()->doorName , '</h2>';
	$lastEvent = '';
	echo '<ul>';
	foreach($doorEvents as $event) {
		if ($lastEvent != $event->eventText) {
			$eventTime = new DateTime($event->eventTimestamp);
			echo '<li class="event'.$event->eventTypeID.'">', $event->eventText , ' - ' , str_replace(' ', '&nbsp;', $eventTime->format('m/d/Y g:i:s A')) , '</li>';
			if ($this->eventTable->hasVideo($event->eventID)) {
			    echo '<video width="280" controls>';
			    echo '   <source src="/video/index/eventid/'.$event->eventID.'" type="video/webm">';
			    echo '</video>';
			}
			
			$lastEvent = $event->eventText;
		}
	}
	echo '</ul>';
	echo '</div>';
}
?>
